"""数据分析 Agent 的业务错误码。

校验与执行失败一律走业务错误码（HTTP 200 + 信封 code），不返回 500——
500 留给真正的服务内部错误。
"""

OUT_OF_SCOPE_CODE = 1101
OUT_OF_SCOPE_MESSAGE = "问题超出可查范围"

GENERATION_FAILED_CODE = 1102
GENERATION_FAILED_MESSAGE = "无法生成查询"

QUERY_REJECTED_CODE = 1103
QUERY_REJECTED_MESSAGE = "查询未通过安全校验"

QUERY_TIMEOUT_CODE = 1104
QUERY_TIMEOUT_MESSAGE = "查询超时"

EXECUTION_FAILED_CODE = 1105
EXECUTION_FAILED_MESSAGE = "查询执行失败"
